/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadBatchRouteImport } from './routes/upload-batch'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MySubmissionsRouteImport } from './routes/my-submissions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReleasesNewRouteImport } from './routes/releases.new'
import { Route as ArtistsNewRouteImport } from './routes/artists.new'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists.$artistId'
import { Route as ApiGenerateArtworkRouteImport } from './routes/api/generate-artwork'
import { Route as ApiGenerateArtistImageRouteImport } from './routes/api/generate-artist-image'
import { Route as AlbumsNewRouteImport } from './routes/albums.new'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums.$albumId'
import { Route as ApiPublicTracksRouteImport } from './routes/api/public/tracks'
import { Route as ApiPublicPodcastsRouteImport } from './routes/api/public/podcasts'
import { Route as ApiPublicArtistsRouteImport } from './routes/api/public/artists'
import { Route as ApiPublicAlbumsRouteImport } from './routes/api/public/albums'
import { Route as AlbumsAlbumIdEditRouteImport } from './routes/albums.$albumId.edit'
import { Route as ApiPublicTracksIdRouteImport } from './routes/api/public/tracks.$id'
import { Route as ApiPublicHooksImportRadioUppsalaRouteImport } from './routes/api/public/hooks/import-radio-uppsala'
import { Route as ApiPublicHooksAudioProcessedRouteImport } from './routes/api/public/hooks/audio-processed'
import { Route as ApiPublicEpisodesIdRouteImport } from './routes/api/public/episodes.$id'
import { Route as ApiPublicArtistsIdRouteImport } from './routes/api/public/artists.$id'
import { Route as ApiPublicAlbumsIdRouteImport } from './routes/api/public/albums.$id'

const UploadBatchRoute = UploadBatchRouteImport.update({
  id: '/upload-batch',
  path: '/upload-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubmissionsRoute = MySubmissionsRouteImport.update({
  id: '/my-submissions',
  path: '/my-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesNewRoute = ReleasesNewRouteImport.update({
  id: '/releases/new',
  path: '/releases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsNewRoute = ArtistsNewRouteImport.update({
  id: '/artists/new',
  path: '/artists/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateArtworkRoute = ApiGenerateArtworkRouteImport.update({
  id: '/api/generate-artwork',
  path: '/api/generate-artwork',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateArtistImageRoute = ApiGenerateArtistImageRouteImport.update({
  id: '/api/generate-artist-image',
  path: '/api/generate-artist-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsNewRoute = AlbumsNewRouteImport.update({
  id: '/albums/new',
  path: '/albums/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTracksRoute = ApiPublicTracksRouteImport.update({
  id: '/api/public/tracks',
  path: '/api/public/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPodcastsRoute = ApiPublicPodcastsRouteImport.update({
  id: '/api/public/podcasts',
  path: '/api/public/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtistsRoute = ApiPublicArtistsRouteImport.update({
  id: '/api/public/artists',
  path: '/api/public/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlbumsRoute = ApiPublicAlbumsRouteImport.update({
  id: '/api/public/albums',
  path: '/api/public/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdEditRoute = AlbumsAlbumIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AlbumsAlbumIdRoute,
} as any)
const ApiPublicTracksIdRoute = ApiPublicTracksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicTracksRoute,
} as any)
const ApiPublicHooksImportRadioUppsalaRoute =
  ApiPublicHooksImportRadioUppsalaRouteImport.update({
    id: '/api/public/hooks/import-radio-uppsala',
    path: '/api/public/hooks/import-radio-uppsala',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAudioProcessedRoute =
  ApiPublicHooksAudioProcessedRouteImport.update({
    id: '/api/public/hooks/audio-processed',
    path: '/api/public/hooks/audio-processed',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEpisodesIdRoute = ApiPublicEpisodesIdRouteImport.update({
  id: '/api/public/episodes/$id',
  path: '/api/public/episodes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArtistsIdRoute = ApiPublicArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicArtistsRoute,
} as any)
const ApiPublicAlbumsIdRoute = ApiPublicAlbumsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicAlbumsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/upload-batch': typeof UploadBatchRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRouteWithChildren
  '/albums/new': typeof AlbumsNewRoute
  '/api/generate-artist-image': typeof ApiGenerateArtistImageRoute
  '/api/generate-artwork': typeof ApiGenerateArtworkRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/artists/new': typeof ArtistsNewRoute
  '/releases/new': typeof ReleasesNewRoute
  '/albums/$albumId/edit': typeof AlbumsAlbumIdEditRoute
  '/api/public/albums': typeof ApiPublicAlbumsRouteWithChildren
  '/api/public/artists': typeof ApiPublicArtistsRouteWithChildren
  '/api/public/podcasts': typeof ApiPublicPodcastsRoute
  '/api/public/tracks': typeof ApiPublicTracksRouteWithChildren
  '/api/public/albums/$id': typeof ApiPublicAlbumsIdRoute
  '/api/public/artists/$id': typeof ApiPublicArtistsIdRoute
  '/api/public/episodes/$id': typeof ApiPublicEpisodesIdRoute
  '/api/public/hooks/audio-processed': typeof ApiPublicHooksAudioProcessedRoute
  '/api/public/hooks/import-radio-uppsala': typeof ApiPublicHooksImportRadioUppsalaRoute
  '/api/public/tracks/$id': typeof ApiPublicTracksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/upload-batch': typeof UploadBatchRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRouteWithChildren
  '/albums/new': typeof AlbumsNewRoute
  '/api/generate-artist-image': typeof ApiGenerateArtistImageRoute
  '/api/generate-artwork': typeof ApiGenerateArtworkRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/artists/new': typeof ArtistsNewRoute
  '/releases/new': typeof ReleasesNewRoute
  '/albums/$albumId/edit': typeof AlbumsAlbumIdEditRoute
  '/api/public/albums': typeof ApiPublicAlbumsRouteWithChildren
  '/api/public/artists': typeof ApiPublicArtistsRouteWithChildren
  '/api/public/podcasts': typeof ApiPublicPodcastsRoute
  '/api/public/tracks': typeof ApiPublicTracksRouteWithChildren
  '/api/public/albums/$id': typeof ApiPublicAlbumsIdRoute
  '/api/public/artists/$id': typeof ApiPublicArtistsIdRoute
  '/api/public/episodes/$id': typeof ApiPublicEpisodesIdRoute
  '/api/public/hooks/audio-processed': typeof ApiPublicHooksAudioProcessedRoute
  '/api/public/hooks/import-radio-uppsala': typeof ApiPublicHooksImportRadioUppsalaRoute
  '/api/public/tracks/$id': typeof ApiPublicTracksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/upload': typeof UploadRoute
  '/upload-batch': typeof UploadBatchRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRouteWithChildren
  '/albums/new': typeof AlbumsNewRoute
  '/api/generate-artist-image': typeof ApiGenerateArtistImageRoute
  '/api/generate-artwork': typeof ApiGenerateArtworkRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/artists/new': typeof ArtistsNewRoute
  '/releases/new': typeof ReleasesNewRoute
  '/albums/$albumId/edit': typeof AlbumsAlbumIdEditRoute
  '/api/public/albums': typeof ApiPublicAlbumsRouteWithChildren
  '/api/public/artists': typeof ApiPublicArtistsRouteWithChildren
  '/api/public/podcasts': typeof ApiPublicPodcastsRoute
  '/api/public/tracks': typeof ApiPublicTracksRouteWithChildren
  '/api/public/albums/$id': typeof ApiPublicAlbumsIdRoute
  '/api/public/artists/$id': typeof ApiPublicArtistsIdRoute
  '/api/public/episodes/$id': typeof ApiPublicEpisodesIdRoute
  '/api/public/hooks/audio-processed': typeof ApiPublicHooksAudioProcessedRoute
  '/api/public/hooks/import-radio-uppsala': typeof ApiPublicHooksImportRadioUppsalaRoute
  '/api/public/tracks/$id': typeof ApiPublicTracksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/catalog'
    | '/login'
    | '/my-submissions'
    | '/notifications'
    | '/settings'
    | '/stats'
    | '/upload'
    | '/upload-batch'
    | '/albums/$albumId'
    | '/albums/new'
    | '/api/generate-artist-image'
    | '/api/generate-artwork'
    | '/artists/$artistId'
    | '/artists/new'
    | '/releases/new'
    | '/albums/$albumId/edit'
    | '/api/public/albums'
    | '/api/public/artists'
    | '/api/public/podcasts'
    | '/api/public/tracks'
    | '/api/public/albums/$id'
    | '/api/public/artists/$id'
    | '/api/public/episodes/$id'
    | '/api/public/hooks/audio-processed'
    | '/api/public/hooks/import-radio-uppsala'
    | '/api/public/tracks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/catalog'
    | '/login'
    | '/my-submissions'
    | '/notifications'
    | '/settings'
    | '/stats'
    | '/upload'
    | '/upload-batch'
    | '/albums/$albumId'
    | '/albums/new'
    | '/api/generate-artist-image'
    | '/api/generate-artwork'
    | '/artists/$artistId'
    | '/artists/new'
    | '/releases/new'
    | '/albums/$albumId/edit'
    | '/api/public/albums'
    | '/api/public/artists'
    | '/api/public/podcasts'
    | '/api/public/tracks'
    | '/api/public/albums/$id'
    | '/api/public/artists/$id'
    | '/api/public/episodes/$id'
    | '/api/public/hooks/audio-processed'
    | '/api/public/hooks/import-radio-uppsala'
    | '/api/public/tracks/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/catalog'
    | '/login'
    | '/my-submissions'
    | '/notifications'
    | '/settings'
    | '/stats'
    | '/upload'
    | '/upload-batch'
    | '/albums/$albumId'
    | '/albums/new'
    | '/api/generate-artist-image'
    | '/api/generate-artwork'
    | '/artists/$artistId'
    | '/artists/new'
    | '/releases/new'
    | '/albums/$albumId/edit'
    | '/api/public/albums'
    | '/api/public/artists'
    | '/api/public/podcasts'
    | '/api/public/tracks'
    | '/api/public/albums/$id'
    | '/api/public/artists/$id'
    | '/api/public/episodes/$id'
    | '/api/public/hooks/audio-processed'
    | '/api/public/hooks/import-radio-uppsala'
    | '/api/public/tracks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  LoginRoute: typeof LoginRoute
  MySubmissionsRoute: typeof MySubmissionsRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  UploadRoute: typeof UploadRoute
  UploadBatchRoute: typeof UploadBatchRoute
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRouteWithChildren
  AlbumsNewRoute: typeof AlbumsNewRoute
  ApiGenerateArtistImageRoute: typeof ApiGenerateArtistImageRoute
  ApiGenerateArtworkRoute: typeof ApiGenerateArtworkRoute
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
  ArtistsNewRoute: typeof ArtistsNewRoute
  ReleasesNewRoute: typeof ReleasesNewRoute
  ApiPublicAlbumsRoute: typeof ApiPublicAlbumsRouteWithChildren
  ApiPublicArtistsRoute: typeof ApiPublicArtistsRouteWithChildren
  ApiPublicPodcastsRoute: typeof ApiPublicPodcastsRoute
  ApiPublicTracksRoute: typeof ApiPublicTracksRouteWithChildren
  ApiPublicEpisodesIdRoute: typeof ApiPublicEpisodesIdRoute
  ApiPublicHooksAudioProcessedRoute: typeof ApiPublicHooksAudioProcessedRoute
  ApiPublicHooksImportRadioUppsalaRoute: typeof ApiPublicHooksImportRadioUppsalaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-batch': {
      id: '/upload-batch'
      path: '/upload-batch'
      fullPath: '/upload-batch'
      preLoaderRoute: typeof UploadBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-submissions': {
      id: '/my-submissions'
      path: '/my-submissions'
      fullPath: '/my-submissions'
      preLoaderRoute: typeof MySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases/new': {
      id: '/releases/new'
      path: '/releases/new'
      fullPath: '/releases/new'
      preLoaderRoute: typeof ReleasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/new': {
      id: '/artists/new'
      path: '/artists/new'
      fullPath: '/artists/new'
      preLoaderRoute: typeof ArtistsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-artwork': {
      id: '/api/generate-artwork'
      path: '/api/generate-artwork'
      fullPath: '/api/generate-artwork'
      preLoaderRoute: typeof ApiGenerateArtworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-artist-image': {
      id: '/api/generate-artist-image'
      path: '/api/generate-artist-image'
      fullPath: '/api/generate-artist-image'
      preLoaderRoute: typeof ApiGenerateArtistImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/new': {
      id: '/albums/new'
      path: '/albums/new'
      fullPath: '/albums/new'
      preLoaderRoute: typeof AlbumsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tracks': {
      id: '/api/public/tracks'
      path: '/api/public/tracks'
      fullPath: '/api/public/tracks'
      preLoaderRoute: typeof ApiPublicTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/podcasts': {
      id: '/api/public/podcasts'
      path: '/api/public/podcasts'
      fullPath: '/api/public/podcasts'
      preLoaderRoute: typeof ApiPublicPodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/artists': {
      id: '/api/public/artists'
      path: '/api/public/artists'
      fullPath: '/api/public/artists'
      preLoaderRoute: typeof ApiPublicArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/albums': {
      id: '/api/public/albums'
      path: '/api/public/albums'
      fullPath: '/api/public/albums'
      preLoaderRoute: typeof ApiPublicAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/edit': {
      id: '/albums/$albumId/edit'
      path: '/edit'
      fullPath: '/albums/$albumId/edit'
      preLoaderRoute: typeof AlbumsAlbumIdEditRouteImport
      parentRoute: typeof AlbumsAlbumIdRoute
    }
    '/api/public/tracks/$id': {
      id: '/api/public/tracks/$id'
      path: '/$id'
      fullPath: '/api/public/tracks/$id'
      preLoaderRoute: typeof ApiPublicTracksIdRouteImport
      parentRoute: typeof ApiPublicTracksRoute
    }
    '/api/public/hooks/import-radio-uppsala': {
      id: '/api/public/hooks/import-radio-uppsala'
      path: '/api/public/hooks/import-radio-uppsala'
      fullPath: '/api/public/hooks/import-radio-uppsala'
      preLoaderRoute: typeof ApiPublicHooksImportRadioUppsalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/audio-processed': {
      id: '/api/public/hooks/audio-processed'
      path: '/api/public/hooks/audio-processed'
      fullPath: '/api/public/hooks/audio-processed'
      preLoaderRoute: typeof ApiPublicHooksAudioProcessedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/episodes/$id': {
      id: '/api/public/episodes/$id'
      path: '/api/public/episodes/$id'
      fullPath: '/api/public/episodes/$id'
      preLoaderRoute: typeof ApiPublicEpisodesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/artists/$id': {
      id: '/api/public/artists/$id'
      path: '/$id'
      fullPath: '/api/public/artists/$id'
      preLoaderRoute: typeof ApiPublicArtistsIdRouteImport
      parentRoute: typeof ApiPublicArtistsRoute
    }
    '/api/public/albums/$id': {
      id: '/api/public/albums/$id'
      path: '/$id'
      fullPath: '/api/public/albums/$id'
      preLoaderRoute: typeof ApiPublicAlbumsIdRouteImport
      parentRoute: typeof ApiPublicAlbumsRoute
    }
  }
}

interface AlbumsAlbumIdRouteChildren {
  AlbumsAlbumIdEditRoute: typeof AlbumsAlbumIdEditRoute
}

const AlbumsAlbumIdRouteChildren: AlbumsAlbumIdRouteChildren = {
  AlbumsAlbumIdEditRoute: AlbumsAlbumIdEditRoute,
}

const AlbumsAlbumIdRouteWithChildren = AlbumsAlbumIdRoute._addFileChildren(
  AlbumsAlbumIdRouteChildren,
)

interface ApiPublicAlbumsRouteChildren {
  ApiPublicAlbumsIdRoute: typeof ApiPublicAlbumsIdRoute
}

const ApiPublicAlbumsRouteChildren: ApiPublicAlbumsRouteChildren = {
  ApiPublicAlbumsIdRoute: ApiPublicAlbumsIdRoute,
}

const ApiPublicAlbumsRouteWithChildren = ApiPublicAlbumsRoute._addFileChildren(
  ApiPublicAlbumsRouteChildren,
)

interface ApiPublicArtistsRouteChildren {
  ApiPublicArtistsIdRoute: typeof ApiPublicArtistsIdRoute
}

const ApiPublicArtistsRouteChildren: ApiPublicArtistsRouteChildren = {
  ApiPublicArtistsIdRoute: ApiPublicArtistsIdRoute,
}

const ApiPublicArtistsRouteWithChildren =
  ApiPublicArtistsRoute._addFileChildren(ApiPublicArtistsRouteChildren)

interface ApiPublicTracksRouteChildren {
  ApiPublicTracksIdRoute: typeof ApiPublicTracksIdRoute
}

const ApiPublicTracksRouteChildren: ApiPublicTracksRouteChildren = {
  ApiPublicTracksIdRoute: ApiPublicTracksIdRoute,
}

const ApiPublicTracksRouteWithChildren = ApiPublicTracksRoute._addFileChildren(
  ApiPublicTracksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  LoginRoute: LoginRoute,
  MySubmissionsRoute: MySubmissionsRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  UploadRoute: UploadRoute,
  UploadBatchRoute: UploadBatchRoute,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRouteWithChildren,
  AlbumsNewRoute: AlbumsNewRoute,
  ApiGenerateArtistImageRoute: ApiGenerateArtistImageRoute,
  ApiGenerateArtworkRoute: ApiGenerateArtworkRoute,
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
  ArtistsNewRoute: ArtistsNewRoute,
  ReleasesNewRoute: ReleasesNewRoute,
  ApiPublicAlbumsRoute: ApiPublicAlbumsRouteWithChildren,
  ApiPublicArtistsRoute: ApiPublicArtistsRouteWithChildren,
  ApiPublicPodcastsRoute: ApiPublicPodcastsRoute,
  ApiPublicTracksRoute: ApiPublicTracksRouteWithChildren,
  ApiPublicEpisodesIdRoute: ApiPublicEpisodesIdRoute,
  ApiPublicHooksAudioProcessedRoute: ApiPublicHooksAudioProcessedRoute,
  ApiPublicHooksImportRadioUppsalaRoute: ApiPublicHooksImportRadioUppsalaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
