/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadBatchRouteImport } from './routes/upload-batch'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MySubmissionsRouteImport } from './routes/my-submissions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists.$artistId'

const UploadBatchRoute = UploadBatchRouteImport.update({
  id: '/upload-batch',
  path: '/upload-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubmissionsRoute = MySubmissionsRouteImport.update({
  id: '/my-submissions',
  path: '/my-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/upload-batch': typeof UploadBatchRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/upload-batch': typeof UploadBatchRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/catalog': typeof CatalogRoute
  '/login': typeof LoginRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/upload-batch': typeof UploadBatchRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog'
    | '/login'
    | '/my-submissions'
    | '/notifications'
    | '/settings'
    | '/upload'
    | '/upload-batch'
    | '/artists/$artistId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/catalog'
    | '/login'
    | '/my-submissions'
    | '/notifications'
    | '/settings'
    | '/upload'
    | '/upload-batch'
    | '/artists/$artistId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog'
    | '/login'
    | '/my-submissions'
    | '/notifications'
    | '/settings'
    | '/upload'
    | '/upload-batch'
    | '/artists/$artistId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CatalogRoute: typeof CatalogRoute
  LoginRoute: typeof LoginRoute
  MySubmissionsRoute: typeof MySubmissionsRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  UploadBatchRoute: typeof UploadBatchRoute
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-batch': {
      id: '/upload-batch'
      path: '/upload-batch'
      fullPath: '/upload-batch'
      preLoaderRoute: typeof UploadBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-submissions': {
      id: '/my-submissions'
      path: '/my-submissions'
      fullPath: '/my-submissions'
      preLoaderRoute: typeof MySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CatalogRoute: CatalogRoute,
  LoginRoute: LoginRoute,
  MySubmissionsRoute: MySubmissionsRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  UploadBatchRoute: UploadBatchRoute,
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
